GET http://localhost:4001/helsingborg/ramlosa

###

POST http://localhost:4001/helsingborg/ramlosa

###

POST http://localhost:4001/helsingborg/ramlosa
x-slack-signature: test
x-slack-request-timestamp: 1700000000